### ISSUE TITLE
It's better to simplify the structure of the code

### ISSUE THREAD

**Issue by BeamReflection** [Nikolai10/MRIC#2]
Thank you very much for the code. It really helps me a lot. But the main code has 900+lines, felt it a little tired to read. Anyway, thank you very much, if there is ant pytorch version, that's really great!

**Comment by Nikolai10** [comment]
Dear @BeamReflection, 

I understand that the main code can be a little overwhelming, especially for people who are new to this field. 

However, please note that our main code intentionally follows the design decisions of [Minnen et al. ICIP 2020](https://github.com/tensorflow/compression/blob/master/models/ms2020.py) (Google Research), which also has about 700+ loc.

MRIC builds on top of this project and adds some additional complexity. In general, I think it's a good idea to familiarize yourself with [tensorflow-compression](https://github.com/tensorflow/compression) first before moving on to more advanced variants.

**Comment by BeamReflection** [comment]
I understand. Thank you very much for your work!

**Comment by BeamReflection** [comment]
> Dear @BeamReflection,
> 
> I understand that the main code can be a little overwhelming, especially for people who are new to this field.
> 
> However, please note that our main code intentionally follows the design decisions of [Minnen et al. ICIP 2020](https://github.com/tensorflow/compression/blob/master/models/ms2020.py) (Google Research), which also has about 700+ loc.
> 
> MRIC builds on top of this project and adds some additional complexity. In general, I think it's a good idea to familiarize yourself with [tensorflow-compression](https://github.com/tensorflow/compression) first before moving on to more advanced variants.

I understand. Thank you very much for your work!

**Comment by BeamReflection** [comment]
Hello, in the config.py, there is a lpips_path, and it points to
res/data/model/lpips_weights. But in this project, it seems that there is
not such a lpips_wights file in the directory:
res/data/model/lpips_weights. Because I want to run the project om my own
PC, not in Google Colab. So, where should I I download this file?

Nikolai Körber ***@***.***> 于2024年8月8日周四 16:44写道：
