### ISSUE TITLE
Questions about inference

### ISSUE THREAD

**Issue by BeamReflection** [Nikolai10/MRIC#4]
I don't know why I encountered the inference problem you mentioned in colab. Is it because of the size of the inference image? I started to infer the default kodim image, and it worked fine, but inference on other images failed. And I tried to infer the kodim image again later, and it also failed. I added the code: os.environ["CUDA_VISIBLE_DEVICES"]="" in the amtm2023.py file as you said, but the previous error still occurred.

**Comment by BeamReflection** [comment]
sorry to bother you, after choosing cpu, it works well. You mentioned in the email that while experimenting with different entropy models, you introduced a bug (not related to machine determinism), resulting in the same error message. I want to know if this bug has been fixed? Because using the CPU to calculate will indeed slow down the speed, which may have a significant impact on actual applications.

**Comment by Nikolai10** [comment]
Hello @BeamReflection,

the bug mentioned in https://groups.google.com/g/tensorflow-compression/c/Tly8q7KoU3Q?pli=1 has been resolved (I actually already don't remember the exact details).

The issues regarding machine determinism however remain. Further assistance may be provided in https://github.com/tensorflow/compression.

Kind regards,
Nikolai
